# Generated by Django 6.1.1 on 2026-09-28 14:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('internal_width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('internal_height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('max_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
    ]
